In [1]:
import numpy as np
import pandas as pd

In [2]:
#loading the dataset

cust_df = pd.read_csv("customer_shopping_behavior.csv")

In [3]:
#checking shape and structure of the dataset

cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [4]:
# the dataset has missing and null values.
# summary statistics

cust_df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
# Imputing missing values in Review Rating column with the median rating of the product category

cust_df["Review Rating"] = cust_df.groupby("Category")["Review Rating"].transform(lambda x : x.fillna(x.median()))

In [6]:
# Renaming columns according to snake casing for better readability and documentation

cust_df.columns = cust_df.columns.str.lower()
cust_df.columns = cust_df.columns.str.replace(" ","_")
cust_df = cust_df.rename(columns={'purchase_amount_(usd)':"purchase_amount"})

In [7]:
cust_df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [8]:
# creating a new column named age_group

age_group = ["Young Adult","Adult","Middle-Aged","Senior"]
cust_df["age_group"] = pd.qcut(cust_df["age"],q=4,labels=age_group)

In [9]:
cust_df[["age","age_group"]].head(10)

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged
5   46  Middle-Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-Aged

In [10]:
# creating new column purchase_frequency_days 

cust_df["frequency_of_purchases"].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [11]:
frequency_mapping = {"Fortnightly":14,
                     "Weekly":7,
                     "Annually":365,
                     "Quarterly":90,
                     "Bi-Weekly":14,
                     "Monthly":30,
                     "Every 3 Months":90
                     }
cust_df['purchase_frequency_days'] = cust_df['frequency_of_purchases'].map(frequency_mapping)

cust_df[["purchase_frequency_days","frequency_of_purchases"]]

      purchase_frequency_days frequency_of_purchases
0                          14            Fortnightly
1                          14            Fortnightly
2                           7                 Weekly
3                           7                 Weekly
4                         365               Annually
...                       ...                    ...
3895                        7                 Weekly
3896                       14              Bi-Weekly
3897                       90              Quarterly
3898                        7                 Weekly
3899                       90              Quarterly

[3900 rows x 2 columns]

In [12]:
#checking if discount_applied and promo_code_applied has the same values or not

(cust_df['discount_applied'] == cust_df['promo_code_used']).all()

np.True_

In [13]:
#dropping promo_code_used for easier analytics

cust_df.drop("promo_code_used",axis=1,inplace=True)

In [14]:
#creating a new column cusdf['customer_segment'] = pd.cut(
cust_df['customer_segment'] = pd.cut(
    cust_df['previous_purchases'],
    bins=[-1, 1, 5, float('inf')],
    labels=['New', 'Returning', 'Loyal']
)
cust_df

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days,customer_segment
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14,Loyal
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14,Returning
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7,Loyal
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7,Loyal
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365,Loyal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7,Loyal
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle-Aged,14,Loyal
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle-Aged,90,Loyal
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7,Loyal
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle-Aged,90,Loyal

In [17]:
cust_df.info()
cust_df.to_csv("customer_shopping_behavior_cleaned.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   object
 3   item_purchased           3900 non-null   object
 4   category                 3900 non-null   object
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   object
 7   size                     3900 non-null   object
 8   color                    3900 non-null   object
 9   season                   3900 non-null   object
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   object
 12  shipping_type            3900 non-null   object
 13  discount_applied         3900 non-null   object
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   object
 16  frequency_of_purchases   3900 non-null   object
 17  age_group                3900 non-null   category
 18  purchase_frequency_days  3900 non-null   int64
 19  customer_segment         3900 non-null   category
dtypes: category(2), float64(1), int64(5), object(12)
memory usage: 556.5+ KB

In [16]:
# exporting dataframe to MySQL

from sqlalchemy import create_engine

# Create connection string
# Format: mysql+mysqlconnector://user:password@host:port/database

engine = create_engine("mysql+mysqlconnector://root:Shubham7@localhost:3306/customer")

# Export DataFrame to MySQL

cust_df.to_sql("shop", con=engine, if_exists="replace", index=False)

print("DataFrame exported to MySQL successfully!")

DataFrame exported to MySQL successfully!